name: Build and run tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-run-tests:
    name: ${{ matrix.config.name }} ${{ matrix.build_type }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              name: "Windows MSVC",
              os: "windows-latest",
              compiler: "-D CMAKE_C_COMPILER=cl -D CMAKE_CXX_COMPILER=cl",
            }
          - {
              name: "Windows Clang",
              os: "windows-latest",
              compiler: "-T ClangCL",
            }
          - {
              name: "Windows GCC",
              os: "windows-latest",
              compiler: "-D CMAKE_C_COMPILER=gcc -D CMAKE_CXX_COMPILER=g++",
            }
          - {
              name: "Linux Clang",
              os: "ubuntu-latest",
              compiler: "-D CMAKE_C_COMPILER=clang -D CMAKE_CXX_COMPILER=clang++",
            }
          - {
              name: "Linux GCC",
              os: "ubuntu-latest",
              compiler: "-D CMAKE_C_COMPILER=gcc -D CMAKE_CXX_COMPILER=g++",
            }
          - {
              name: "MacOS Clang",
              os: macos-latest,
              compiler: "-D CMAKE_C_COMPILER=$(brew --prefix llvm@15)/bin/clang -D CMAKE_CXX_COMPILER=$(brew --prefix llvm@15)/bin/clang++",
            }
          - {
              name: "MacOS GCC",
              os: macos-latest,
              compiler: "-D CMAKE_C_COMPILER=gcc -D CMAKE_CXX_COMPILER=g++",
            }
        build_type:
          - Debug
          - Release

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ matrix.config.name }}-${{ matrix.build_type }}

      - name: Build
        uses: lukka/run-cmake@v3
        with:
          cmakeListsOrSettingsJson: "CMakeListsTxtAdvanced"
          cmakeListsTxtPath: "${{ github.workspace }}/tests/CMakeLists.txt"
          cmakeBuildType: ${{ matrix.build_type }}
          buildDirectory: "${{ github.workspace }}/build"
          cmakeAppendedArgs: " -D WARNINGS_AS_ERRORS_FOR_EXE_PATH=ON -D CMAKE_BUILD_TYPE=${{ matrix.build_type }} ${{ matrix.config.compiler }} -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache"
          buildWithCMakeArgs: "--config ${{ matrix.build_type }} --target exe_path-tests"

      - name: Run
        run: ${{github.workspace}}/build/exe_path-tests
