name: Build and run tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  target: exe_path-tests # Should be the name of the target you created in your CMakeLists.txt and want to build and run

jobs:
  build-and-run-tests:
    name: ${{ matrix.config.name }} ${{ matrix.build_type }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              name: Windows MSVC,
              os: windows-latest,
              compiler: -D CMAKE_C_COMPILER=cl -D CMAKE_CXX_COMPILER=cl,
            }
          - { name: Windows Clang, os: windows-latest, compiler: -T ClangCL }
          - {
              name: Windows GCC,
              os: windows-latest,
              compiler: -D CMAKE_C_COMPILER=gcc -D CMAKE_CXX_COMPILER=g++ -GNinja,
            }
          - {
              name: Linux Clang,
              os: ubuntu-latest,
              compiler: -D CMAKE_C_COMPILER=clang -D CMAKE_CXX_COMPILER=clang++,
            }
          - {
              name: Linux GCC,
              os: ubuntu-latest,
              compiler: -D CMAKE_C_COMPILER=gcc -D CMAKE_CXX_COMPILER=g++,
            }
          - {
              name: MacOS Clang,
              os: macos-latest,
              compiler: -D CMAKE_C_COMPILER=clang -D CMAKE_CXX_COMPILER=clang++,
            }
          - {
              name: MacOS GCC,
              os: macos-latest,
              compiler: -D CMAKE_C_COMPILER=gcc -D CMAKE_CXX_COMPILER=g++,
            }
        build_type:
          - Debug
          - Release

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      #   - uses: msys2/setup-msys2@v2
      #     if: matrix.config.name == 'Windows GCC'
      #     with:
      #       update: true
      #       install: >-
      #         mingw-w64-x86_64-ninja

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ matrix.config.name }}-${{ matrix.build_type }}

      - name: Build
        uses: lukka/run-cmake@v3
        with:
          cmakeListsTxtPath: ${{ github.workspace }}/tests/CMakeLists.txt
          cmakeAppendedArgs: -D WARNINGS_AS_ERRORS_FOR_EXE_PATH=ON -D CMAKE_BUILD_TYPE=${{ matrix.build_type }} ${{ matrix.config.compiler }} -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache
          buildWithCMakeArgs: --config ${{ matrix.build_type }} --target ${{env.target}}
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeBuildType: ${{ matrix.build_type }}
          buildDirectory: ${{ github.workspace }}/build

      - name: Run
        if: runner.os == 'Windows' && matrix.config.name != 'Windows GCC'
        run: ${{github.workspace}}\build\${{ matrix.build_type }}\${{env.target}}.exe
      - name: Run
        if: runner.os != 'Windows' || matrix.config.name == 'Windows GCC'
        run: ${{github.workspace}}/build/${{env.target}}
