name: Build and run tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-run-tests:
    name: ${{ matrix.config.name }} ${{ matrix.build_type }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: "Windows MSVC", os: windows-latest, cc: "cl", cxx: "cl" }
          - { name: "Windows MinGW", os: windows-latest, cc: "gcc", cxx: "g++" }
          - { name: "Ubuntu GCC", os: ubuntu-latest, cc: "gcc", cxx: "g++" }
          - {
              name: "MacOS Clang",
              os: macos-latest,
              cc: "clang",
              cxx: "clang++",
            }
        build_type:
          - Debug
          - Release

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.1
        with:
          key: ${{ matrix.config.name }}-${{ matrix.build_type }}

      - name: build with cmake
        uses: lukka/run-cmake@v3
        with:
          cmakeListsTxtPath: "${{ github.workspace }}/tests/CMakeLists.txt"
          cmakeAppendedArgs: "-DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache"
          buildWithCMake: true
          buildDirectory: "${{ github.workspace }}/build"

      - name: Run
        run: ${{github.workspace}}/build/${{ matrix.build_type }}/exe_path-tests
